apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-two
  namespace: app-demo
  labels:
    app: webapp-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-two
  template:
    metadata:
      labels:
        app: webapp-two
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 20
        volumeMounts:
        - name: web-content-two
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: web-content-two
        configMap:
          name: webapp-content-two