apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: app-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / #Without the nginx.ingress.kubernetes.io/rewrite-target: / annotation, NGINX ingress just passes the full path (/deploymentone or /deploymenttwo) → your nginx container can’t serve it.
spec:
  ingressClassName: nginx
  rules:
  - host: webapp.local
    http:
      paths:
      - path: /deploymentone
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 80
      - path: /deploymenttwo
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80        